format = """
[╭─](color_fg)\
[ ](bg:color_bg)\
$directory\
[�](fg:color_bg bg:color_cursor)\
$git_branch\
$git_status\
[�](fg:color_cursor)\
\n[╰─](color_fg) $character"""

[directory]
style = "fg:color_fg bg:color_bg"
format = "[ $path ]($style)"
truncation_length = 3
truncate_to_repo = false

[git_branch]
style = "fg:color_bg bg:color_cursor"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "fg:color_bg bg:color_cursor"
format = "[$all_status$ahead_behind ]($style)"

[character]
success_symbol = "[❯](bold color_fg)"
error_symbol = "[❯](bold red)"

[palettes.kakku]
color_bg = "#f8fafc"
color_fg = "#182033"
color_cursor = "#f97316"

palette = "kakku"
