background {
    monitor =
    path = ~/.config/hypr/wallpaper.png
    blur_passes = 2
    blur_size = 4
}

input-field {
    monitor =
    size = 320, 58
    position = 0, -130
    halign = center
    valign = center
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.18
    outer_color = rgba(c73f5fff)
    inner_color = rgba(160d12ee)
    font_color = rgba(f4dce5ff)
    placeholder_text = Password
    fail_text = Try again
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgba(f4dce5ff)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 60
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%A, %d %B"
    color = rgba(f4dce5ff)
    font_size = 18
    font_family = Inter
    position = 0, 8
    halign = center
    valign = center
}

label {
    monitor =
    text = KakkuOS
    color = rgba(f4dce5ff)
    font_size = 22
    font_family = Inter
    position = 0, -58
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] whoami
    color = rgba(f4dce5ff)
    font_size = 14
    font_family = Inter
    position = 0, -92
    halign = center
    valign = center
}
