# ~/.config/mpv/mpv.conf

# Video
vo=gpu-next
gpu-api=vulkan
hwdec=auto-safe

# Audio
volume=80
volume-max=150

# OSD
osd-font="JetBrainsMono Nerd Font"
osd-font-size=24
osd-duration=2000

# Subtitles
sub-auto=fuzzy
sub-font="sans-serif"
sub-font-size=36

# Window
autofit-larger=90%x90%
keep-open=yes
save-position-on-quit=yes

# Screenshots
screenshot-format=png
screenshot-directory=~/Pictures/Screenshots
screenshot-template="%F-%P"
