color_theme = "TTY"
theme_background = False
truecolor = True
rounded_corners = True
shown_boxes = "cpu mem net proc"
update_ms = 1500
proc_sorting = "cpu lazy"
proc_reversed = False
proc_tree = False
proc_colors = True
proc_gradient = True
proc_per_core = False
proc_mem_bytes = True
proc_cpu_graphs = True
show_uptime = True
check_temp = True
cpu_sensor = "Auto"
show_coretemp = True
show_cpu_freq = True
show_battery = True
show_init = False
net_download = 100
net_upload = 100
