XDG_CURRENT_DESKTOP=niri
XDG_SESSION_DESKTOP=niri
XDG_SESSION_TYPE=wayland
QT_QPA_PLATFORM=wayland;xcb
QT_QPA_PLATFORMTHEME=qt6ct
QT_AUTO_SCREEN_SCALE_FACTOR=1
XCURSOR_THEME=breeze_cursors
XCURSOR_SIZE=24
MESA_SHADER_CACHE_MAX_SIZE=12G
__GL_SHADER_DISK_CACHE_SIZE=12000000000
MOZ_ENABLE_WAYLAND=1
NIXOS_OZONE_WL=1
ELECTRON_OZONE_PLATFORM_HINT=auto
SDL_VIDEODRIVER=wayland,x11
CLUTTER_BACKEND=wayland
_JAVA_AWT_WM_NONREPARENTING=1
